---
- name: Web Server Deployment
  hosts: test
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Start Apache2 Service
      service:
        name: apache2
        state: started

    - name: Copy HTML File to Web Server
      copy:
        src: /opt/index.html
        dest: /var/www/html/

    - name: Restart Apache2 Service
      service:
        name: apache2
        state: restarted

